---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-video-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: amazon-prime-video
  template:
    metadata:
      labels:
        app: amazon-prime-video
    spec:
      containers:
      - name: amazon-prime-video-container
        image: aseemakram19/amazon-prime-video
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-video-service
spec:
  type: LoadBalancer
  selector:
    app: amazon-prime-video
  ports:
  - port: 80
    targetPort: 3000
